# Utilisez l'image OpenJDK 11 de Docker Hub
FROM openjdk:11

# Créez un répertoire pour l'application
WORKDIR /app

# Copiez le jar de votre application dans le conteneur
COPY target/achat.jar /app/achat.jar

# Exposez le port 8080 utilisé par Spring Boot
EXPOSE 8080

# Commande à exécuter lorsque le conteneur démarre
CMD ["java", "-jar", "achat.jar"]