version: '1.2'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysqldb-data:/var/lib/mysql
  app-achat:
    depends_on:
      - mysqldb
    image: nourgh/achat:1.0.0
    restart: on-failure
    ports:
      - 8089:8089
volumes:
  mysqldb-data: